<?php
/**
 * Created by PhpStorm.
 * User: code
 * Date: 2019/4/18
 * Time: 11:08
 */

namespace app\admin\controller;

use app\admin\model\Article;
use app\admin\model\Category;

class Articles extends BaseMould
{
    //模型名字
    public $mouldname = 'article';
    //自身模型实例
    public $m;
    //添加数据


    public function _initialize()
    {
        //调用父类的构造函数
        parent::_initialize();
        $this->m = new Article;

    }

    public function index($id=0)
    {
        return parent::index(); // TODO: Change the autogenerated stub
    }

    public function add()
    {

        //准备上级栏目下拉内容
        $mv =array();
        $category = new Category;
        $category->getTree(0, $mv);
        $carr = $category->getSelectArray($mv,array(0=>'顶级栏目'));

        foreach ($this->field as $k=>$val) {
            if($val['fieldname'] == 'cid')
            {
                $this->field[$k]['vdefault'] = $carr;
            }
        }

        return parent::add(); // TODO: Change the autogenerated stub
    }

    public function edit($id)
    {

        //准备上级栏目下拉内容
        $mv =array();
        $category = new Category;
        $category->getTree(0, $mv);
        $carr = $category->getSelectArray($mv,array(0=>'顶级栏目'));

        foreach ($this->field as $k=>$val) {
            if($val['fieldname'] == 'cid')
            {
                $this->field[$k]['vdefault'] = $carr;
                $this->field[$k]['isAdd'] = 1;
            }elseif ($val['fieldname'] == 'recommend')
            {
                $this->field[$k]['isAdd'] = 1;
            }
        }
        return parent::edit($id); // TODO: Change the autogenerated stub
    }

}
