<?php
/**
 * Created by PhpStorm.
 * User: code
 * Date: 2019/4/20
 * Time: 14:31
 */

namespace app\admin\controller;

use app\admin\model\Card;
use app\admin\model\Member;

class Cards extends BaseMould
{
    //模型名字
    public $mouldname = 'card';
    //自身模型实例
    public $m;


    public function _initialize()
    {
        //调用父类的构造函数
        parent::_initialize();
        $this->m = new Card;
    }


    public function index()
    {
        return parent::index(); // TODO: Change the autogenerated stub
    }
}